[Bootstrap] fix npm.cmd shim resolution (#38022)
fix npm.cmd shim resolution

The `script/web_discovery_project.py` will invoke `npm` on Windows
platforms by appending a `.cmd`:

```
NPM = 'npm'
if PLATFORM in ['win32', 'cygwin']:
    NPM += '.cmd'
```

This means that shim resolution fails and errors out with:

```
FileNotFoundError: [WinError 2] The system cannot find the file specified
Error: Command 'vpython3.bat script/web_discovery_project.py --install' returned non-zero exit status 1 in D:\brave-browser\src/brave
```

This fix adds the missing shim, using a verbatim copy of `npm.bat`.